# (CI/SCHEDULE/MANUAL TRIGGER)
name: qTest-MSTest-Parser

on:
  push:
    branches: [ main, dev ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  schedule:
    - cron:  '0 0 1 */3 *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-2022, macos-11 ]
        node-version: [ 14.x, 16.x, 17.x, 18.x ]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
    
    - name: Upload Artifact
      if: ${{ matrix.os == 'ubuntu-20.04' && matrix.node-version == '16.x' }}
      uses: actions/upload-artifact@v4
      with:
        name: qtest-mstest-parser
        path: |
          ${{ github.workspace }}/node_modules
          package-lock.json
          package.json
          parser.js
        retention-days: 90
