# (CI/SCHEDULE/MANUAL TRIGGER)
name: qTest-MSTest-Parser

on:
  push:
    branches: [ main, dev ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  schedule:
    - cron:  '0 0 1 */3 *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node-version: [ 14.x, 16.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
    
    - name: Upload Artifact
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.node-version == '14.x' }}
      uses: actions/upload-artifact@v2
      with:
        name: qtest-mstest-parser
        path: |
          ${{ github.workspace }}/node_modules
          package-lock.json
          package.json
          parser.js
        retention-days: 90
