name: Release

env:
    RELEASE_NAME: "v.1.0.5"
    RELEASE_NOTES: |
      - Security Update - Uncontrolled resource consumption in braces [CVE-2024-4068](https://github.com/advisories/GHSA-grv7-fg5c-xmjg)
      - Security Update - Regular Expression Denial of Service (ReDoS) in micromatch [CVE-2024-4067](https://github.com/advisories/GHSA-952p-6rrq-rcjv)
    
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        node-version: [ 16.x ]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'qtest-mstest-parser.zip'
        path: |
          node_modules
          package-lock.json
          package.json
          parser.js
        
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.RELEASE_NAME }}
        body: ${{ env.RELEASE_NOTES }}
        draft: false
        prerelease: false
        artifacts: "qtest-mstest-parser.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
