name: Release

env:
    RELEASE_NAME: "v.1.0.4"
    RELEASE_NOTES: |
      - Security Update - 'decode-uri-component' vulnerable to Denial of Service (DoS) [CVE-2022-38900](https://github.com/advisories/GHSA-w573-4hg7-7wgq)
      - Security Update - 'minimatch' ReDoS vulnerability [CVE-2022-3517](https://github.com/advisories/GHSA-f8q6-p94x-37v3)
      - Security Update - 'xml2js' is vulnerable to prototype pollution [CVE-2023-0842](https://github.com/advisories/GHSA-776f-qx25-q3cc)
    
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        node-version: [ 16.x ]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'qtest-mstest-parser.zip'
        path: |
          node_modules
          package-lock.json
          package.json
          parser.js
        
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.RELEASE_NAME }}
        body: ${{ env.RELEASE_NOTES }}
        draft: false
        prerelease: false
        artifacts: "qtest-mstest-parser.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
