name: Release

env:
    RELEASE_NAME: "v.1.0.3"
    RELEASE_NOTES: |
      - Sofware Release (qTest-MSTest-Parser)
      - No change to qTest-MSTest-Parser
      - Security Update - 'glob-parent' dependency update to latest version (6.0.2) to avoid [CVE-2020-28469](https://github.com/advisories/GHSA-ww39-953v-wcq6)
    
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        node-version: [ 16.x ]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'qtest-mstest-parser.zip'
        path: |
          node_modules
          package-lock.json
          package.json
          parser.js
        
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.RELEASE_NAME }}
        body: ${{ env.RELEASE_NOTES }}
        draft: false
        prerelease: false
        artifacts: "qtest-mstest-parser.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
